// File: Sources/RatatuiKit/Events.swift
// Role: Decodes raw RffiEvent structs from the CRatatuiFFI poll call into the
//       Swift Event enum consumed by MoonSwiftTUI's EventPump. All decoding
//       is pure — the EventPump calls poll(timeout:) then hands the result up.
// Upstream: CRatatuiFFI (rffi_poll_event, RffiEvent, RffiEvent field constants)
// Downstream: MoonSwiftTUI/App/EventPump.swift (calls poll, receives Event)

import CRatatuiFFI
import Foundation

// MARK: - KeyCode

/// A decoded key code from a terminal key event.
///
/// `.char(Unicode.Scalar)` carries the Unicode scalar for printable characters
/// (e.g. `'a'`, `'A'`, `'€'`). Named keys cover the special-key vocabulary
/// of crossterm's `KeyCode` enum; `unknown` preserves any code not yet
/// mapped so the pump never silently drops input.
public enum KeyCode: Sendable, Equatable {
    case char(Unicode.Scalar)
    case backspace
    case enter
    case left
    case right
    case up
    case down
    case home
    case end
    case pageUp
    case pageDown
    case tab
    case backTab
    case delete
    case insert
    case f(UInt8)            // F1–F12; value is the function-key number
    case escape
    case capsLock
    case scrollLock
    case numLock
    case printScreen
    case pause
    case menu
    case null
    case unknown(UInt32)     // preserves unmapped codes for forward compat
}

// MARK: - KeyModifiers

/// Modifier keys active during a key event.
///
/// This is a Swift `OptionSet` matching the shim's `key_mods` bitfield:
/// `SHIFT = 1`, `ALT = 2`, `CTRL = 4` (values from the generated header).
public struct KeyModifiers: OptionSet, Sendable {
    public let rawValue: UInt8

    public init(rawValue: UInt8) { self.rawValue = rawValue }

    /// The Shift key.
    public static let shift = KeyModifiers(rawValue: 1)
    /// The Alt / Option key.
    public static let alt   = KeyModifiers(rawValue: 2)
    /// The Control key.
    public static let ctrl  = KeyModifiers(rawValue: 4)
}

// MARK: - MouseKind / MouseButton

/// The kind of mouse event received.
public enum MouseKind: UInt32, Sendable {
    case down       = 0
    case up         = 1
    case drag       = 2
    case moved      = 3
    case scrollDown = 4
    case scrollUp   = 5
    case scrollLeft = 6
    case scrollRight = 7
}

/// The mouse button associated with a mouse event.
public enum MouseButton: UInt32, Sendable {
    case left   = 0
    case right  = 1
    case middle = 2
    case none   = 3
}

// MARK: - Event

/// A decoded terminal event, ready for the EventPump to post as an AppEvent.
///
/// `Event` maps one-to-one with `RffiEvent` fields; no information is lost.
/// The EventPump decodes via `Event(from:)` and forwards to the EventChannel.
public enum Event: Sendable {
    /// A key was pressed.
    case key(KeyCode, modifiers: KeyModifiers)
    /// The terminal was resized to the given dimensions (columns × rows).
    case resize(cols: UInt16, rows: UInt16)
    /// A mouse event occurred at the given cell position.
    case mouse(
        kind: MouseKind,
        button: MouseButton,
        col: UInt16,
        row: UInt16,
        modifiers: KeyModifiers
    )
    /// Bracketed-paste content received.
    case paste(String)
}

// MARK: - RffiEvent discriminant constants

// Mirror the numeric discriminants the Rust side writes into `RffiEvent.kind`.
// Verified against ratatui_ffi.h / events.rs — these are compile-time constants
// in the generated header, so a mismatch is a build error, not a silent bug.
private enum RffiEventKind: UInt32 {
    case key    = 0
    case resize = 1
    case mouse  = 2
    case paste  = 3
}

// crossterm KeyCode numeric mapping — generated by the Rust shim.
// Partial list; sufficient for P1 key dispatch. Unknown codes fall through
// to `.unknown(code)` for forward compatibility.
private enum RffiKeyCode: UInt32 {
    case backspace   = 0
    case enter       = 1
    case left        = 2
    case right       = 3
    case up          = 4
    case down        = 5
    case home        = 6
    case end         = 7
    case pageUp      = 8
    case pageDown    = 9
    case tab         = 10
    case backTab     = 11
    case delete      = 12
    case insert      = 13
    case f1          = 14
    case f2          = 15
    case f3          = 16
    case f4          = 17
    case f5          = 18
    case f6          = 19
    case f7          = 20
    case f8          = 21
    case f9          = 22
    case f10         = 23
    case f11         = 24
    case f12         = 25
    case char        = 26   // key_char field carries the Unicode codepoint
    case escape      = 27
    case capsLock    = 28
    case scrollLock  = 29
    case numLock     = 30
    case printScreen = 31
    case pause       = 32
    case menu        = 33
    case null        = 34
}

// MARK: - Event decoding

extension Event {

    /// Decodes a raw `RffiEvent` struct into a Swift `Event`.
    ///
    /// Returns `nil` for discriminant values that are not yet mapped —
    /// the caller should treat an unknown event kind as a no-op rather than
    /// crashing, preserving forward compatibility with new shim versions.
    ///
    /// Convenience wrapper over `init?(reading:)` for callers that hold the
    /// event by value. Prefer `init?(reading:)` where the event is already
    /// addressable: `RffiEvent` is ~4 KB (inline paste buffer), and by-value
    /// passing multiplies 4 KB stack copies in unoptimized builds — enough to
    /// overflow the small stacks swift-testing runs tests on (CI SIGBUS in
    /// `__chkstk_darwin`).
    public init?(from raw: RffiEvent) {
        let decoded = withUnsafePointer(to: raw) { Event(reading: $0) }
        guard let decoded else { return nil }
        self = decoded
    }

    /// Decodes the `RffiEvent` at `raw` into a Swift `Event` without copying
    /// the ~4 KB struct.
    ///
    /// This is the single place in RatatuiKit that reads raw `RffiEvent`
    /// fields; tests construct `RffiEvent` values (heap-boxed) and pass them
    /// here to verify decoding without a real terminal.
    public init?(reading raw: UnsafePointer<RffiEvent>) {
        switch raw.pointee.kind {
        case RffiEventKind.key.rawValue:
            let code = KeyCode(rawKeyCode: raw.pointee.key_code, charScalar: raw.pointee.key_char)
            let mods = KeyModifiers(rawValue: raw.pointee.key_mods)
            self = .key(code, modifiers: mods)

        case RffiEventKind.resize.rawValue:
            self = .resize(cols: raw.pointee.resize_cols, rows: raw.pointee.resize_rows)

        case RffiEventKind.mouse.rawValue:
            let kind = MouseKind(rawValue: raw.pointee.mouse_kind) ?? .moved
            let button = MouseButton(rawValue: raw.pointee.mouse_button) ?? .none
            let mods = KeyModifiers(rawValue: raw.pointee.mouse_mods)
            self = .mouse(
                kind: kind,
                button: button,
                col: raw.pointee.mouse_col,
                row: raw.pointee.mouse_row,
                modifiers: mods
            )

        case RffiEventKind.paste.rawValue:
            self = .paste(pasteText(reading: raw))

        default:
            return nil
        }
    }
}

// MARK: - KeyCode decoding

private extension KeyCode {

    /// Maps the shim's numeric key code + optional char codepoint to a `KeyCode`.
    init(rawKeyCode: UInt32, charScalar: UInt32) {
        switch RffiKeyCode(rawValue: rawKeyCode) {
        case .backspace:   self = .backspace
        case .enter:       self = .enter
        case .left:        self = .left
        case .right:       self = .right
        case .up:          self = .up
        case .down:        self = .down
        case .home:        self = .home
        case .end:         self = .end
        case .pageUp:      self = .pageUp
        case .pageDown:    self = .pageDown
        case .tab:         self = .tab
        case .backTab:     self = .backTab
        case .delete:      self = .delete
        case .insert:      self = .insert
        case .f1:          self = .f(1)
        case .f2:          self = .f(2)
        case .f3:          self = .f(3)
        case .f4:          self = .f(4)
        case .f5:          self = .f(5)
        case .f6:          self = .f(6)
        case .f7:          self = .f(7)
        case .f8:          self = .f(8)
        case .f9:          self = .f(9)
        case .f10:         self = .f(10)
        case .f11:         self = .f(11)
        case .f12:         self = .f(12)
        case .escape:      self = .escape
        case .capsLock:    self = .capsLock
        case .scrollLock:  self = .scrollLock
        case .numLock:     self = .numLock
        case .printScreen: self = .printScreen
        case .pause:       self = .pause
        case .menu:        self = .menu
        case .null:        self = .null
        case .char:
            // Unicode scalar from key_char field; 0 is invalid (treated as unknown).
            if charScalar != 0, let scalar = Unicode.Scalar(charScalar) {
                self = .char(scalar)
            } else {
                self = .unknown(charScalar)
            }
        case nil:
            self = .unknown(rawKeyCode)
        }
    }
}

// MARK: - Paste text extraction

/// Extracts the NUL-terminated paste text from an `RffiEvent.paste_buf`.
///
/// The shim guarantees NUL-termination and that `paste_len` is the byte count
/// excluding the NUL. We use `paste_len` for the slice bound to avoid reading
/// past the real content, then decode as UTF-8 with lossy fallback for any
/// malformed sequences the terminal might have injected.
///
/// Pointer-based to avoid materialising the ~4 KB `paste_buf` tuple on the
/// stack (see `Event.init?(reading:)` rationale).
private func pasteText(reading raw: UnsafePointer<RffiEvent>) -> String {
    let byteCount = Int(raw.pointee.paste_len)
    guard let bufOffset = MemoryLayout<RffiEvent>.offset(of: \.paste_buf) else {
        return ""
    }
    let base = UnsafeRawPointer(raw) + bufOffset
    let bytes = UnsafeRawBufferPointer(
        start: base,
        count: min(byteCount, Int(PASTE_BUF_BYTES))
    )
    return String(decoding: bytes, as: UTF8.self)
}

// MARK: - EventSource (poll entry point)

/// Polls for the next terminal event, blocking for at most `timeout`.
///
/// Returns a decoded `Event` on success, `nil` on timeout. Throws `FFIError`
/// on an I/O error.
///
/// EINTR: the shim retries internally — the caller never observes EINTR as an
/// error (ARCHITECTURE.md §5.2).
///
/// Thread class: input-class — must be called exclusively from the EventPump
/// thread. Debug builds assert this.
///
/// - Parameters:
///   - timeout: Maximum wait; clamped to Int32.max milliseconds (~24 days).
///   - pumpThread: The EventPump's thread object, used for the debug assertion.
/// - Returns: A decoded `Event`, or `nil` if the timeout elapsed.
/// - Throws: `FFIError` on an I/O error from the shim.
public func pollEvent(
    timeout: Duration,
    pumpThread: Thread
) throws -> Event? {
    assertInputClass(pumpThread: pumpThread)

    // Convert Duration to milliseconds, clamped to Int32 range.
    let ms = Int32(
        clamping: Int64(timeout.components.seconds) * 1_000
                + Int64(timeout.components.attoseconds / 1_000_000_000_000_000)
    )

    // Heap-allocate the ~4 KB RffiEvent rather than placing it on the stack:
    // decode then reads it in place via Event(reading:) with zero copies.
    let raw = UnsafeMutablePointer<RffiEvent>.allocate(capacity: 1)
    defer { raw.deallocate() }
    raw.initialize(to: RffiEvent())

    let status = rffi_poll_event(raw, ms)

    if status == RFFI_TIMEOUT {
        return nil
    }
    if status != 0 {
        throw FFIError(code: status, message: FFIError.lastErrorMessage())
    }
    // `nil` means an unknown event kind — treat as no-op (forward compat).
    return Event(reading: raw)
}
