// File: Tests/MoonSwiftTUITests/HighlighterTests.swift
// Location: MoonSwiftTUITests/
// Role: Tests for the Highlighter component. Verifies:
//   1. Specific token kinds appear at expected ranges for Lua source.
//   2. LRU cache evicts the least-recently-used entry at capacity without error.
//   3. Incremental re-parse after an edit: spans are produced correctly.
//   4. First-render-unhighlighted contract via the Reducer.
//   5. CaptureMapping produces the correct ThemeToken per ux-spec.md §8.2.
//
// Threading: Highlighter posts results asynchronously on its serial queue.
// Tests poll a real EventChannel using drainAll() inside a retry loop with a
// 5-second deadline — generous enough to tolerate CI thread starvation (80 ms+).
//
// Timing notes: never use fixed sleeps. The retry loop below checks every 10 ms
// and gives up after 5 seconds total.

import CryptoKit
import Foundation
import MoonSwiftCore
import Testing

@testable import MoonSwiftTUI

// MARK: - Async result collection helper

/// Poll `channel` until a `.highlightReady` event for `id` arrives or the
/// deadline passes.
///
/// Uses `Task.sleep` to yield between polls so other tasks can run.
/// - Parameters:
///   - channel: The channel to poll.
///   - id:      The source ID to wait for.
///   - deadline: Seconds to wait before giving up (default 5).
/// - Returns: The spans from the first matching event, or `nil` on timeout.
private func waitForHighlight(
    channel: EventChannel,
    id: SourceID,
    deadline: TimeInterval = 5
) async -> [HighlightSpan]? {
    let start = Date()
    while Date().timeIntervalSince(start) < deadline {
        let events = channel.drainAll()
        for event in events {
            if case .highlightReady(let eid, let spans) = event, eid == id {
                return spans
            }
        }
        // Yield for 10 ms between polls.
        try? await Task.sleep(nanoseconds: 10_000_000)
    }
    return nil
}

/// Run a single highlight request and return the spans, or fail the test on timeout.
private func highlight(
    _ id: SourceID = SourceID(path: "test.lua"),
    text: String,
    deadline: TimeInterval = 5
) async -> [HighlightSpan]? {
    let highlighter = Highlighter()
    let channel = EventChannel()
    highlighter.highlight(id, text: text, via: channel)
    return await waitForHighlight(channel: channel, id: id, deadline: deadline)
}

// MARK: - Fragment factory

private func makeFragment(id: SourceID, code: String) -> LuaSourceFragment {
    let data = Data(code.utf8)
    let hash = SHA256.hash(data: data)
    let url = URL(fileURLWithPath: "/test/\(id.path)")
    let prov = FragmentProvenance(
        file: url,
        jsonpath: id.jsonpath,
        document: id.document,
        byteRange: 0..<data.count,
        lineOffset: 0,
        contentHash: hash
    )
    return LuaSourceFragment(code: code, provenance: prov)
}

// MARK: - Fixture loader

/// Load the `sample.lua` fixture.
///
/// `Bundle.module` is generated by SPM for every target with resources, but
/// `@testable import MoonSwiftTUI` pulls `MoonSwiftCore`'s `Bundle.module` into
/// scope, making the name ambiguous. To sidestep this, resolve the fixture via
/// `#filePath`: at compile time Swift bakes in the absolute path of this source
/// file, so we can navigate from the test-source directory to the fixture.
private func sampleLua(file: StaticString = #filePath) throws -> String {
    // #filePath resolves to the absolute path of this .swift file at compile time.
    // The fixture lives at: <this-file's-dir>/Fixtures/sample.lua
    let thisFile = URL(fileURLWithPath: "\(file)")
    let fixtureURL =
        thisFile
        .deletingLastPathComponent()
        .appendingPathComponent("Fixtures")
        .appendingPathComponent("sample.lua")

    guard let text = try? String(contentsOf: fixtureURL, encoding: .utf8) else {
        struct FixtureMissing: Error {}
        throw FixtureMissing()
    }
    return text
}

// MARK: - Lua span tests

@Suite("Highlighter — Lua spans")
struct HighlighterLuaTests {

    @Test("local keyword produces .keyword span at column 0 of line 0")
    func localKeywordSpan() async {
        let spans = await highlight(text: "local x = 42")
        #expect(spans != nil, "Highlight must complete within timeout")
        guard let spans else { return }

        let keywordSpans = spans.filter { $0.tokenKind == .keyword }
        #expect(!keywordSpans.isEmpty, "Expected keyword spans")

        // 'local' is at (0, 0) with length 5.
        let local = keywordSpans.first { $0.line == 0 && $0.column == 0 }
        #expect(local != nil, "Expected 'local' span at (line=0, col=0)")
        #expect(local?.length == 5, "Expected 'local' span length == 5")
    }

    @Test("string literal produces .string span")
    func stringLiteralSpan() async {
        let spans = await highlight(text: #"local s = "hello""#)
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let stringSpans = spans.filter { $0.tokenKind == .string }
        #expect(!stringSpans.isEmpty, "Expected at least one string span")
    }

    @Test("line comment produces .comment span at (0, 0)")
    func lineCommentSpan() async {
        let spans = await highlight(text: "-- comment\nlocal x = 1")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let comments = spans.filter { $0.tokenKind == .comment }
        #expect(!comments.isEmpty, "Expected comment span")
        let atOrigin = comments.first { $0.line == 0 && $0.column == 0 }
        #expect(atOrigin != nil, "Comment must start at (0, 0)")
    }

    @Test("number literal produces .number span")
    func numberLiteralSpan() async {
        let spans = await highlight(text: "local n = 42")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let numbers = spans.filter { $0.tokenKind == .number }
        #expect(!numbers.isEmpty, "Expected number span for '42'")
    }

    @Test("function name produces .function span")
    func functionNameSpan() async {
        // Named function definition: name node captured as @function
        let spans = await highlight(text: "function greet(name) end")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let funcSpans = spans.filter { $0.tokenKind == .function }
        #expect(!funcSpans.isEmpty, "Expected .function span for 'greet'")
    }

    @Test("nil / true / false produce .keyword spans")
    func builtinConstantSpans() async {
        let spans = await highlight(text: "local a = nil\nlocal b = true\nlocal c = false")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        // Expect at least one keyword span per line containing nil/true/false.
        let line0Keys = spans.filter { $0.tokenKind == .keyword && $0.line == 0 }
        let line1Keys = spans.filter { $0.tokenKind == .keyword && $0.line == 1 }
        let line2Keys = spans.filter { $0.tokenKind == .keyword && $0.line == 2 }
        #expect(!line0Keys.isEmpty, "Expected keyword span (nil or local) on line 0")
        #expect(!line1Keys.isEmpty, "Expected keyword span (true or local) on line 1")
        #expect(!line2Keys.isEmpty, "Expected keyword span (false or local) on line 2")
    }

    @Test("return keyword appears in spans")
    func returnKeyword() async {
        let spans = await highlight(text: "local function f() return 1 end")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let keywords = spans.filter { $0.tokenKind == .keyword }
        #expect(!keywords.isEmpty, "Expected keyword spans (local, function, return, end)")
    }

    @Test("sample.lua fixture produces spans for all expected token kinds")
    func fixtureAllTokenKinds() async throws {
        let text = try sampleLua()
        let id = SourceID(path: "sample.lua")
        let spans = await highlight(id, text: text)
        #expect(spans != nil, "Fixture highlight must complete")
        guard let spans else { return }

        #expect(!spans.isEmpty, "Fixture must produce non-empty spans")
        let kinds = Set(spans.map { $0.tokenKind })
        #expect(kinds.contains(.keyword), "sample.lua must have keyword spans")
        #expect(kinds.contains(.comment), "sample.lua must have comment spans")
        #expect(kinds.contains(.string), "sample.lua must have string spans")
        #expect(kinds.contains(.number), "sample.lua must have number spans")
    }

    @Test("spans on a single line are non-overlapping")
    func noOverlapOnSingleLine() async {
        let spans = await highlight(text: "local x = 42 -- end")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        let line0 = spans.filter { $0.line == 0 }.sorted { $0.column < $1.column }
        var maxEnd = 0
        for span in line0 {
            #expect(
                span.column >= maxEnd,
                "Spans must not overlap: \(span.column) < maxEnd \(maxEnd)"
            )
            maxEnd = max(maxEnd, span.column + span.length)
        }
    }

    @Test("spans have non-negative lines, columns, and positive lengths")
    func spansAreValid() async {
        let spans = await highlight(text: "local x = 1\n-- comment\nreturn x")
        #expect(spans != nil, "Highlight must complete")
        guard let spans else { return }

        for span in spans {
            #expect(span.line >= 0, "Span line must be non-negative")
            #expect(span.column >= 0, "Span column must be non-negative")
            #expect(span.length > 0, "Span length must be positive")
        }
    }
}

// MARK: - LRU eviction tests

@Suite("Highlighter — LRU cache")
struct HighlighterLRUTests {

    @Test("evicting 10 sources (beyond capacity 8) does not lose results")
    func evictionCompletesAllRequests() async {
        let highlighter = Highlighter()
        var results: [(SourceID, [HighlightSpan]?)] = []

        // Submit requests sequentially, one at a time, to keep the test simple.
        // The LRU capacity is 8; after 8 distinct IDs the oldest is evicted.
        for i in 0..<10 {
            let id = SourceID(path: "evict\(i).lua")
            let channel = EventChannel()
            highlighter.highlight(id, text: "local x = \(i)", via: channel)
            let spans = await waitForHighlight(channel: channel, id: id, deadline: 5)
            results.append((id, spans))
        }

        for (id, spans) in results {
            #expect(spans != nil, "Source \(id) must complete after eviction")
        }
    }

    @Test("target source re-highlighted after being evicted still produces spans")
    func reHighlightAfterEviction() async {
        let highlighter = Highlighter()
        let target = SourceID(path: "target.lua")

        // Initial parse — caches the tree.
        let ch1 = EventChannel()
        highlighter.highlight(target, text: "local x = 1", via: ch1)
        let first = await waitForHighlight(channel: ch1, id: target, deadline: 5)
        #expect(first != nil, "First highlight must complete")

        // Fill cache to evict 'target' (capacity = 8, push 8 more distinct IDs).
        for i in 0..<8 {
            let id = SourceID(path: "filler\(i).lua")
            let ch = EventChannel()
            highlighter.highlight(id, text: "local y = \(i)", via: ch)
            _ = await waitForHighlight(channel: ch, id: id, deadline: 5)
        }

        // Re-highlight target after eviction — full re-parse, no cached tree.
        let ch2 = EventChannel()
        highlighter.highlight(target, text: "local x = 2", via: ch2)
        let second = await waitForHighlight(channel: ch2, id: target, deadline: 5)
        #expect(second != nil, "Re-highlight after eviction must complete")
        #expect(second?.isEmpty == false, "Re-highlight must produce spans")
    }
}

// MARK: - Incremental re-parse tests

@Suite("Highlighter — Incremental re-parse")
struct HighlighterIncrementalTests {

    @Test("re-parse after numeric edit produces updated number span")
    func incrementalReparseSameID() async {
        let highlighter = Highlighter()
        let id = SourceID(path: "incr.lua")

        // First parse.
        let ch1 = EventChannel()
        highlighter.highlight(id, text: "local n = 1", via: ch1)
        let first = await waitForHighlight(channel: ch1, id: id, deadline: 5)
        #expect(first != nil, "First parse must complete")

        // Re-parse after changing the number.
        let ch2 = EventChannel()
        highlighter.highlight(id, text: "local n = 999", via: ch2)
        let second = await waitForHighlight(channel: ch2, id: id, deadline: 5)
        #expect(second != nil, "Incremental re-parse must complete")

        // Both parses must include a number span on line 0.
        let n1 = first?.filter { $0.tokenKind == .number && $0.line == 0 }
        let n2 = second?.filter { $0.tokenKind == .number && $0.line == 0 }
        #expect(n1?.isEmpty == false, "First parse: number span on line 0")
        #expect(n2?.isEmpty == false, "Second parse: number span on line 0")
    }

    @Test("adding a comment line on edit produces a comment span")
    func addCommentLine() async {
        let highlighter = Highlighter()
        let id = SourceID(path: "edit.lua")

        // Initial parse — no comment.
        let ch1 = EventChannel()
        highlighter.highlight(id, text: "local x = 1", via: ch1)
        _ = await waitForHighlight(channel: ch1, id: id, deadline: 5)

        // Edit: prepend a comment line.
        let ch2 = EventChannel()
        highlighter.highlight(id, text: "-- new comment\nlocal x = 1", via: ch2)
        let after = await waitForHighlight(channel: ch2, id: id, deadline: 5)
        #expect(after != nil, "Re-parse after adding comment must complete")
        let comments = after?.filter { $0.tokenKind == .comment } ?? []
        #expect(!comments.isEmpty, "Re-parse must include comment span for new comment line")
    }
}

// MARK: - First-render-unhighlighted contract (pure reducer tests)

@Suite("Highlighter — First-render contract via Reducer")
struct HighlighterFirstRenderTests {

    @Test("highlight is nil before .highlightReady (unhighlighted on first render)")
    func noSpansBeforeHighlightReady() {
        let id = SourceID(path: "init.lua")
        let state = AppState()
        // Before any .highlightReady event, highlight[id] must be nil.
        #expect(state.highlight[id] == nil, "No spans before .highlightReady")
    }

    @Test(".highlightReady populates AppState.highlight (second render has spans)")
    func highlightReadyPopulatesState() {
        let id = SourceID(path: "init.lua")
        let state = AppState()
        let spans = [HighlightSpan(line: 0, column: 0, length: 5, tokenKind: .keyword)]

        let (next, _) = reduce(state, .highlightReady(id, spans: spans))
        #expect(next.highlight[id] == spans, "After .highlightReady, spans must be stored")
    }

    @Test("sourceLoaded requests a .highlight effect (scheduling mechanism)")
    func sourceLoadedRequestsHighlight() {
        let id = SourceID(path: "loaded.lua")
        let state = AppState()
        let fragment = makeFragment(id: id, code: "return 1")

        let (_, effects) = reduce(state, .sourceLoaded(id: id, fragment: fragment))
        let hasHighlight = effects.contains {
            if case .highlight(let eid) = $0 { return eid == id }
            return false
        }
        #expect(hasHighlight, "sourceLoaded must schedule .highlight effect")
    }

    @Test(".highlightReady replaces previous spans for the same source")
    func highlightReadyReplacesPrevious() {
        let id = SourceID(path: "init.lua")
        var state = AppState()
        state.highlight[id] = [HighlightSpan(line: 0, column: 0, length: 3, tokenKind: .comment)]

        let newSpans = [HighlightSpan(line: 0, column: 0, length: 5, tokenKind: .keyword)]
        let (next, _) = reduce(state, .highlightReady(id, spans: newSpans))
        #expect(next.highlight[id]?.count == 1)
        #expect(next.highlight[id]?.first?.tokenKind == .keyword)
    }
}

// MARK: - CaptureMapping unit tests (ux-spec.md §8.2)

@Suite("CaptureMapping — ux-spec §8.2 exact mapping")
struct CaptureMappingTests {

    @Test("keyword family → .keyword (7 names)")
    func keywordFamily() {
        let names = [
            "keyword",
            "keyword.function",
            "keyword.return",
            "keyword.operator",
            "keyword.conditional",
            "keyword.repeat",
            "keyword.exception",
        ]
        for name in names {
            #expect(CaptureMapping.token(for: name) == .keyword, "\(name) → .keyword")
        }
    }

    @Test("string.escape → .keyword (reuses keyword pink per spec)")
    func stringEscape() {
        #expect(CaptureMapping.token(for: "string.escape") == .keyword)
    }

    @Test("variable.builtin → .keyword (_G, _ENV, self)")
    func variableBuiltin() {
        #expect(CaptureMapping.token(for: "variable.builtin") == .keyword)
    }

    @Test("constant.builtin → .keyword (nil, true, false)")
    func constantBuiltin() {
        #expect(CaptureMapping.token(for: "constant.builtin") == .keyword)
    }

    @Test("label → .keyword (goto labels)")
    func labelCapture() {
        #expect(CaptureMapping.token(for: "label") == .keyword)
    }

    @Test("string → .string")
    func stringCapture() {
        #expect(CaptureMapping.token(for: "string") == .string)
    }

    @Test("comment → .comment")
    func commentCapture() {
        #expect(CaptureMapping.token(for: "comment") == .comment)
    }

    @Test("number → .number, constant → .number")
    func numberFamily() {
        #expect(CaptureMapping.token(for: "number") == .number)
        #expect(CaptureMapping.token(for: "constant") == .number)
    }

    @Test("function / method / constructor / type → .function (function_name role)")
    func functionFamily() {
        let names = ["function", "method", "constructor", "type"]
        for name in names {
            #expect(CaptureMapping.token(for: name) == .function, "\(name) → .function")
        }
    }

    @Test("variable / field / parameter → .variable (identifier role)")
    func variableFamily() {
        let names = ["variable", "field", "parameter"]
        for name in names {
            #expect(CaptureMapping.token(for: name) == .variable, "\(name) → .variable")
        }
    }

    @Test("operator → .operatorToken")
    func operatorCapture() {
        #expect(CaptureMapping.token(for: "operator") == .operatorToken)
    }

    @Test("punctuation.bracket / punctuation.delimiter → .variable (identifier role)")
    func punctuationCaptures() {
        #expect(CaptureMapping.token(for: "punctuation.bracket") == .variable)
        #expect(CaptureMapping.token(for: "punctuation.delimiter") == .variable)
    }

    @Test("unknown captures fall back to .variable (identifier role)")
    func fallback() {
        #expect(CaptureMapping.token(for: "unknown.capture") == .variable)
        #expect(CaptureMapping.token(for: "") == .variable)
        #expect(CaptureMapping.token(for: "xyz") == .variable)
    }
}
